Repository modern-agile-team/dongurami-front, pull requests merged in 2021-09, with the labels that each got.

#121 Fix(soonki/clubhome): 동아리 소개 페이지에서 overflow시 스크롤이 안되는 버그 수정 #120
  src/components/ClubHome/Intro/Desc.js
  src/styles/Club/Home/Common/frame.module.scss
  src/styles/Club/Home/Intro/ClubIntro.module.scss
  src/styles/Club/Home/Intro/Desc.module.scss
Labels: error

#124 Modify(seohyun/login): 로그인 페이지 UI 개선
  src/components/SignUp/SignUpForm.js
  src/components/login/Login.js
  src/styles/User/Login/Login.module.scss
  src/styles/User/SignUp/SignUp.module.scss
  src/styles/User/SignUp/SignUpForm.module.scss
Labels: new, style

#128 Modify(seohyun/Header): 목록이 아닌 부분의 cursor가 pointer로 지속되는 현상 개선
  src/components/Common/Header.js
  src/styles/Common/Header.module.scss
Labels: error, update

#130 Add(seohyun/find): 아이디/비밀번호 찾기 페이지 생성 밎 ui 구현 후 라우팅
  src/components/Find/FindID.js
  src/components/Find/FindPW.js
  src/components/login/Login.js
  src/pages/findID.js
  src/pages/findPW.js
  src/styles/User/Find/FindID.module.scss
  src/styles/User/Find/FindPW.module.scss
Labels: new, style

#129 Modify(soonki/clubNotice): 동아리 공지사항에 UI 적용
  src/components/ClubHome/ClubNotice.js
  src/components/ClubHome/ClubNoticePagination.js
  src/components/ClubHome/ClubNoticeSearch.js
  src/components/ClubHome/ClubNoticeTable.js
  src/components/ClubHome/Notice/ClubNotice.js
  src/components/ClubHome/Notice/ClubNoticePagination.js
  src/components/ClubHome/Notice/ClubNoticeSearch.js
  src/components/ClubHome/Notice/ClubNoticeTable.js
  src/components/ClubHome/Review/ReviewMine.js
  src/components/ClubHome/common/frame.js
  src/styles/Club/Home/Notice/ClubNotice.module.scss
  src/styles/Club/Home/Notice/ClubNoticePagination.module.scss
  src/styles/Club/Home/Notice/ClubNoticeSearch.module.scss
  src/styles/Club/Home/Notice/ClubNoticeTable.module.scss
  src/styles/Club/Home/Review/ReviewList.module.scss
  src/styles/Club/Home/Review/ReviewMine.module.scss
Labels: update

#134 Refactor(soonki/font): global font 적용
  src/styles/Club/Home/Activities/Modal.module.scss
  src/styles/global.scss
Labels: style, refactor

#139 Add(junsang/board): 게시판 글, 게시판 글 작성 페이지 추가
  src/components/Common/Comment/AddComment.js
  src/components/Notice/Notice.js
  src/components/Notice/NoticePagination.js
  src/components/Notice/NoticeSearch.js
  src/components/Notice/NoticeTable.js
  src/components/Write/ReactQuillContainer.js
  src/components/Write/Write.js
  src/styles/Board/Notice/Notice.module.scss
  src/styles/Board/Post/PostContent.module.scss
  src/styles/Board/Write/Write.module.scss
  src/styles/Common/Comment/AddComment.module.scss
  src/styles/Common/Comment/Comment.module.scss
  src/styles/Common/Comment/ReplyComment.module.scss
  src/styles/global.scss
Labels: new

#138 Add(seohyun/Header): 헤더 반응형 구현 및 ui 개선
  src/components/Common/Header.js
  src/styles/Common/Header.module.scss
Labels: new, update, style

#141 Add(soonki/apply): 동아리 지원하기 페이지 생성 및 UI 구현
  src/components/ClubHome/Apply/Additional.js
  src/components/ClubHome/Apply/Apply.js
  src/components/ClubHome/Apply/ApplyHeader.js
  src/components/ClubHome/Apply/ApplyQuestions.js
  src/styles/Club/Home/Apply/Additional.module.scss
  src/styles/Club/Home/Apply/Apply.module.scss
  src/styles/Club/Home/Apply/ApplyHeader.module.scss
  src/styles/Club/Home/Apply/ApplyQuestions.module.scss
Labels: new

#145 Modify(seohyun/Header): Header 반응형 기능 개선
  src/components/Common/Header.js
  src/styles/Common/Header.module.scss
Labels: update

#146 Modify(seohyun/signUp): 회원가입 페이지 반응형 구현 및 개선
  src/components/SignUp/SignUpForm.js
  src/styles/User/SignUp/SignUpForm.module.scss
Labels: update, style

#148 Modify(seohyun/login): 로그인,아이디/비번찾기 페이지 반응형 구현
  src/components/login/Login.js
  src/styles/User/Find/FindID.module.scss
  src/styles/User/Find/FindPW.module.scss
  src/styles/User/Login/Login.module.scss
Labels: update, style

#155 Add(soonki/manager): 동아리 관리 페이지 가입 승인 대기 추가
  src/components/ClubHome/Manager/Approve.js
  src/components/ClubHome/Manager/ApproveHeader.js
  src/components/ClubHome/Manager/ApproveList.js
  src/components/ClubHome/Manager/Manager.js
  src/components/ClubHome/Manager/Members.js
  src/components/ClubHome/Manager/MembersHeader.js
  src/components/ClubHome/Manager/MembersMember.js
  src/components/ClubHome/Manager/MembersPreface.js
  src/styles/Club/Home/Manager/Approve.module.scss
  src/styles/Club/Home/Manager/ApproveList.module.scss
  src/styles/Club/Home/Manager/Manager.module.scss
Labels: new

#158 Update(soonki/clubintro): 동아리 소개 UI 개선 및 반응형 구현
  src/components/ClubHome/Intro/ClubInfo.js
  src/components/ClubHome/Intro/Desc.js
  src/styles/Club/Home/Intro/ClubInfo.module.scss
  src/styles/Club/Home/Intro/ClubIntro.module.scss
  src/styles/Club/Home/Intro/Desc.module.scss
Labels: update, style

#162 Add(seohyun/main): 메인화면 UI 구축
  package-lock.json
  package.json
  src/components/Common/Footer.js
  src/components/main/ClubPromotion.js
  src/components/main/Intro.js
  src/components/main/OurIntro.js
  src/components/main/ServiceLogo.js
  src/pages/index.js
  src/styles/Common/Footer.module.scss
  src/styles/Main/ClubPromotion.module.scss
  src/styles/Main/Intro.module.scss
  src/styles/Main/OurIntro.module.scss
  src/styles/Main/ServiceLogo.module.scss
Labels: new, style

#160 Modify(soonki/activities): 동아리 활동 내용 페이지 modal창 반응형 위치 변경 #118
  src/components/ClubHome/Activities/ModalFooter.js
  src/components/ClubHome/Activities/ModalHeader.js
  src/components/ClubHome/Activities/ModalImg.js
  src/components/ClubHome/Intro/ClubInfo.js
  src/components/ClubHome/Intro/Desc.js
  src/components/ClubHome/common/frame.js
  src/styles/Club/Home/Activities/Activities.module.scss
  src/styles/Club/Home/Activities/Modal.module.scss
  src/styles/Club/Home/Activities/ModalFooter.module.scss
  src/styles/Club/Home/Activities/ModalHeader.module.scss
  src/styles/Club/Home/Activities/ModalImg.module.scss
  src/styles/Club/Home/Common/SideBar.module.scss
  src/styles/Club/Home/Intro/ClubInfo.module.scss
  src/styles/Club/Home/Intro/Desc.module.scss
Labels: update

#167 Modify(seohyun/main): 메인 애니매이션 추가
  package-lock.json
  package.json
  src/components/main/ClubPromotion.js
  src/components/main/Intro.js
  src/components/main/OurIntro.js
  src/components/main/ServiceLogo.js
  src/styles/Main/ClubPromotion.module.scss
Labels: new, style

#169 Modify(seohyun/main): 메인 UI 반응형 구현
  src/components/main/ClubPromotion.js
  src/styles/Main/ClubPromotion.module.scss
  src/styles/Main/Intro.module.scss
  src/styles/Main/OurIntro.module.scss
  src/styles/Main/ServiceLogo.module.scss
Labels: update, style

#168 Modify(soonki/review): 동아리 후기 UI 개선 #118
  src/components/ClubHome/Review/ReviewHeader.js
  src/components/ClubHome/Review/ReviewList.js
  src/components/ClubHome/Review/ReviewMine.js
  src/components/ClubHome/Review/backup.js
  src/styles/Club/Home/Activities/Modal.module.scss
  src/styles/Club/Home/Activities/ModalHeader.module.scss
  src/styles/Club/Home/Activities/ModalImg.module.scss
  src/styles/Club/Home/Review/Review.module.scss
  src/styles/Club/Home/Review/ReviewFilter.module.scss
  src/styles/Club/Home/Review/ReviewHeader.module.scss
  src/styles/Club/Home/Review/ReviewList.module.scss
  src/styles/Club/Home/Review/ReviewMine.module.scss
  src/styles/Club/Home/Review/ReviewWrite.module.scss
Labels: update, style

#174 Add(seohyun/all): 모든 페이지 Footer 적용
  src/components/Common/Header.js
  src/components/Post/Post.js
  src/components/SignUp/SignUp.js
  src/pages/ClubHome.js
  src/pages/LoginPage.js
  src/pages/clublists.js
  src/pages/findID.js
  src/pages/findPW.js
  src/pages/manager.js
  src/pages/notice.js
  src/pages/promotion.js
  src/styles/User/SignUp/SignUp.module.scss
  src/styles/User/SignUp/SignUpForm.module.scss
Labels: new

#178 Add(junsang/changePassword): 비밀번호 변경 페이지 구현
  src/components/ChangePW/ChagePW.js
  src/components/ChangePW/Change.js
  src/components/ChangePW/Check.js
  src/components/ChangePassword/ChagePassWord.js
  src/pages/changepassword.js
  src/styles/User/ChangePassword/ChangePassword.module.scss
  src/styles/User/PasswordChange/Change.module.scss
  src/styles/User/PasswordChange/Check.module.scss
Labels: new

#184 Modify(junsang/board): 게시판 css 조정
  src/components/Board/Board.js
  src/styles/Board/Board/Pagination.module.scss
  src/styles/Board/Board/Table.module.scss
Labels: style

#185 Modify(seohyun/user): 로그인/회원가입 등 유저관련 페이지 모바일 반응형 구현
  src/components/Common/Header.js
  src/components/Find/FindID.js
  src/components/Find/FindPW.js
  src/components/login/Login.js
  src/styles/Common/Header.module.scss
  src/styles/User/Find/FindID.module.scss
  src/styles/User/Find/FindPW.module.scss
  src/styles/User/Login/Login.module.scss
  src/styles/User/SignUp/SignUpForm.module.scss
Labels: update

#189 Modify(seohyun/Header): 헤더 반응형 및 UI 개선
  src/components/Common/Header.js
  src/styles/Common/Header.module.scss
Labels: update, style

#194 Add(junsang/board): 게시판 글 목록 페이지 api 연동
  src/components/Board/Board.js
  src/components/Board/Pagination.js
  src/components/Board/Table.js
  src/components/Common/Header.js
  src/pages/freeboard.js
  src/pages/notice.js
  src/styles/Board/Board/Table.module.scss
Labels: new

#191 Add(soonki/intro): 동아리 소개 수정 api 적용
  src/components/ClubHome/Intro/ClubIntro.js
  src/components/ClubHome/Intro/Desc.js
  src/components/ClubHome/Review/Review.js
  src/components/ClubHome/Review/ReviewMine.js
  src/components/ClubHome/Review/ReviewWrite.js
  src/styles/Club/Home/Intro/ClubIntro.module.scss
  src/styles/Club/Home/Intro/Desc.module.scss
Labels: new

#196 Modify(seohyun/Main): 메인화면 모바일 반응형 구현
  src/styles/Common/Footer.module.scss
  src/styles/Common/Header.module.scss
  src/styles/Main/ClubPromotion.module.scss
  src/styles/Main/Intro.module.scss
  src/styles/Main/OurIntro.module.scss
  src/styles/Main/ServiceLogo.module.scss
Labels: update, style

#201 Fix(soonki/clubHome): 모바일 화면에서 사이드바가 깨지던 이슈 수정 #200
  src/components/ClubHome/Review/Review.js
  src/components/ClubHome/Review/ReviewWrite.js
  src/styles/Club/Home/Activities/Activities.module.scss
  src/styles/Club/Home/Common/SideBar.module.scss
  src/styles/Club/Home/Intro/ClubInfo.module.scss
  src/styles/Club/Home/Intro/ClubIntro.module.scss
  src/styles/Club/Home/Intro/Desc.module.scss
  src/styles/Club/Home/Notice/ClubNotice.module.scss
  src/styles/Club/Home/Review/Review.module.scss
  src/styles/Club/Home/Review/ReviewHeader.module.scss
  src/styles/Club/Home/Review/ReviewList.module.scss
  src/styles/Club/Home/Review/ReviewMine.module.scss
  src/styles/Club/Home/Review/ReviewWrite.module.scss
  src/styles/Common/Footer.module.scss
Labels: error

#227 Modify(seohyun/user): 회원가입 기능구현 및 JWT localstorage 저장
  src/components/Common/Header.js
  src/components/SignUp/SignUpForm.js
  src/components/login/Login.js
  src/styles/Common/Header.module.scss
  src/styles/User/SignUp/SignUpForm.module.scss
Labels: update

#232 Add(soonki/apply): 동아리 지원하기 페이지 api 적용
  src/components/ClubHome/Apply/Additional.js
  src/components/ClubHome/Apply/Apply.js
  src/components/ClubHome/Apply/ApplyQuestions.js
  src/components/ClubHome/Apply/ApplySubmit.js
  src/components/ClubHome/Intro/ClubInfo.js
  src/components/ClubHome/Manager/Approve.js
  src/components/ClubHome/Review/Review.js
  src/styles/Club/Home/Apply/Apply.module.scss
  src/styles/Club/Home/Apply/ApplySubmit.module.scss
Labels: new

#265 Modify(soonki/manager): 관리자 페이지 UI 조금 수정
  src/components/ClubHome/Activities/Act.js
  src/components/ClubHome/Manager/ApproveHeader.js
  src/components/ClubHome/Manager/Manager.js
  src/components/ClubHome/Manager/ManagerHeader.js
  src/components/ClubHome/Manager/Members.js
  src/components/ClubHome/Manager/MembersHeader.js
  src/components/ClubHome/Manager/MembersList.js
  src/components/ClubHome/Manager/MembersPreface.js
  src/styles/Club/Home/Manager/ApproveList.module.scss
  src/styles/Club/Home/Manager/Manager.module.scss
  src/styles/Club/Home/Manager/ManagerHeader.module.scss
  src/styles/Club/Home/Manager/ManagerPreface.module.scss
  src/styles/Club/Home/Manager/MembersList.module.scss
Labels: style
