Repository modern-agile-team/dongurami-front, pull requests merged in 2022-01, with the labels that each got.

#740 Fix(soonki/clubs): 동아리 홈 API 변경에 따른 오류 수정
  src/components/Club/Home/Activities/index.js
  src/components/Club/Home/Apply/ApplyHeader.js
  src/components/Club/Home/Apply/index.js
  src/components/Club/Home/Intro/Desc.js
  src/components/Club/Home/Intro/Info/Basic/SexRatio.js
  src/components/Club/Home/Intro/Info/Logo/ClubLogo.js
  src/components/Club/Home/Intro/Info/index.js
  src/components/Club/Home/Intro/index.js
  src/components/Club/Home/Review/ReviewHeader.js
  src/components/Club/Home/Review/index.js
  src/components/Club/Home/SideBar.js
  src/components/Club/Home/index.js
Labels: error

#744 Modify(bumsoo/clublist): 동아리 목록 검색 api 수정사항 반영
  src/apis/clublist.js
  src/components/Club/ClubLists/index.js
Labels: update

#742 Fix(hyunwoo/board): 게시판 라우팅 에러 수정
  src/components/Board/Table/Table.js
  src/components/Board/Table/Tr.js
Labels: error

#746 Fix(hyunwoo/calendar): 일정 페이지 api 변경사항 반영
  src/components/Club/Home/Calendar/index.js
Labels: refactor

#749 Fix(hyunwoo/calendar): 리덕스 요청에서도 api 변경사항 적용
  src/components/Club/Home/Calendar/Schedule/Schedule.js
Labels: error

#748 Delete(soonki/manager): 가입 승인 거절 body에서 필요없는 내용 제거 #747
  src/components/Club/Home/Manager/index.js
Labels: update

#750 Refactor(Soonki/alarm): 알람 삭제 API 함수명 변경
  src/apis/alarm.js
  src/components/Common/Alarm/index.js
Labels: refactor

#751 Add(soonki/manager): 가입 승인 거절 알람 API 추가 #747
  src/apis/alarm.js
  src/components/Club/Home/Manager/index.js
Labels: new, update

#753 Fix(hyunwoo/board): 게시판 알림api 도입
  src/apis/board.js
  src/components/Common/Comment/AddComment.js
  src/components/Common/Comment/CommentContainer.js
Labels: refactor

#755 Refactor(hyunwoo/calendar): 일정부분 알람 기능 api 도입
  src/apis/calendar.js
  src/components/Club/Home/Calendar/index.js
Labels: refactor

#757 Add(hyunwoo/board): 게시판 댓글, 답글 알림 생성 api 도입
  src/apis/board.js
  src/apis/post.js
  src/components/Board/index.js
  src/components/Common/Comment/AddComment.js
  src/components/Common/Comment/Comment.js
  src/components/Post/Post.js
  src/components/Write/Write.js
Labels: new

#760 Fix(soonki/apply): 관리자 페이지 API 변경에 따른 코드 수정
  src/components/Club/Home/Apply/ApplyBody.js
  src/components/Club/Home/Apply/Question/Question.js
  src/components/Club/Home/Apply/Submit/ApplySubmit.js
  src/components/Club/Home/Apply/index.js
Labels: error

#761 Add(hyunwoo/profile): 동아리 탈퇴 알림 api 도입
  src/apis/profile.js
  src/components/User/Profile/index.js
Labels: new

#763 Fix(hyunwoo/board): 검색 기능 오류 수정
  src/apis/board.js
  src/redux/slices/board.js
Labels: error

#769 Fix(hyunwoo/board): api 수정사항 반영
  README.md
  src/apis/post.js
  src/components/Common/Comment/AddComment.js
  src/components/Post/Post.js
Labels: refactor

#767 Fix(hyunwoo/profile): 스크랩페이지 api 응답데이터 키값 수정
  src/components/User/Profile/MyPost/MyPost.js
  src/components/User/Profile/Scraps/ScrapItems.js
  src/components/User/Profile/Scraps/Scraps.js
  src/components/User/Profile/Scraps/WriteScraps/Edit.js
  src/components/User/Profile/Scraps/WriteScraps/PostContainer.js
  src/components/User/Profile/Scraps/WriteScraps/WriteScraps.js
  src/components/User/Profile/index.js
Labels: refactor

#772 Fix(hyunwoo/board): 동아리 공지 게시판 api 수정사항 반영
  src/apis/post.js
Labels: refactor

#773 Modify(soonki/promotion): 홍보 게시글 스피너 적용
  src/components/Promotion/Post/Poster.js
  src/components/Promotion/Post/index.js
  src/redux/slices/post.js
Labels: update

#771 Modify(soonki/clubhome): 스켈레톤 UI 방식 변경
  src/components/Club/Home/Intro/index.js
  src/components/Club/Home/Skeleton.js
  src/components/Club/Home/index.js
  src/redux/slices/clubhome.js
Labels: update

#775 Add(hyunwoo/clubActivity): 동아리 활동내용 포스트 클릭시 스피너 적용
  src/apis/board.js
  src/components/Club/Home/Activities/ActivityPost.js
  src/components/Write/Write.js
  src/redux/slices/post.js
Labels: refactor

#776 Fix(soonki/message)동아리 홈에서 홍보게시판 넘어갈 때 발생하는 오류 수정
  src/components/User/Message/SendMessage/index.js
Labels: error

#777 Fix(hyunwoo/board): 홍보게시판 댓글 api 수정사항 반영
  src/apis/promotion.js
  src/redux/slices/post.js
Labels: refactor
